wininjob_admin:
    resource: "@WininjobAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

wininjob_test:
    resource: "@WininjobTestBundle/Controller/"
    type:     annotation
    prefix:   /

